#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Split the upstream chart showcase into a hub-and-spoke set of Jekyll pages.

The showcase is generated by TerraFluent.Chart.Reporting itself and mirrored
into this repo by mirror-docs.sh, so it cannot be hand-edited: the next mirror
run would overwrite the edits. This script is the site-side generator. It reads
the mirrored source once and emits every derived page, so re-mirroring the
library and re-running this produces the same split against the new specimens.

Input
  _showcase-source/showcase.html   upstream, verbatim (written by mirror-docs.sh)
  docs/chart/chart-types.md        upstream docs; the C# snippets are lifted from
                                   here rather than written by hand, so they are
                                   always the library's real API
  _data/chart_types.yml            the hand-written prose

Output
  chart/showcase/index.html        the hub: a linked index, no specimens
  chart/types/<slug>/index.html    27 chart-type pages
  chart/features/<slug>/index.html  8 feature pages
  chart/cookbook/index.html        the recipe cookbook
  _data/chart_spokes.yml           the generated URL list, consumed by the hub
                                   layout and by the llms.txt block

Every specimen SVG is moved, never copied and never re-rendered, so each one
lives at exactly one URL. Run with --check to verify without writing.
"""

from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "_showcase-source" / "showcase.html"
DOCS_TYPES = ROOT / "docs" / "chart" / "chart-types.md"
PROSE = ROOT / "_data" / "chart_types.yml"
SPOKES_YML = ROOT / "_data" / "chart_spokes.yml"

# ---------------------------------------------------------------------------
# Classification of the 102 upstream cards.
#
# Card numbers are 1-based and match the "NN — Title" headings in the upstream
# showcase. `docs` is the "## N." section in docs/chart/chart-types.md the C#
# snippet is lifted from, and `block` selects which ```csharp fence inside it
# (section 6 documents Pie and Donut together, so they differ only by block).
# ---------------------------------------------------------------------------

TYPES: dict[str, dict] = {
    "line":         {"cards": [1],      "docs": 1,  "method": "AddLine", "block": 0},
    "spline":       {"cards": [7, 11],  "docs": 2,  "method": "AddSpline", "block": 0},
    "area":         {"cards": [3],      "docs": 3,  "method": "AddArea", "block": 0},
    "column":       {"cards": [4],      "docs": 4,  "method": "AddColumn", "block": 0},
    "bar":          {"cards": [12],     "docs": 5,  "method": "AddBar", "block": 0},
    "pie":          {"cards": [6, 28],  "docs": 6,  "method": "Add + .AsPie()", "block": 0},
    "donut":        {"cards": [18, 37, 38], "docs": 6, "method": "Add + .AsPie() + .DonutHole()", "block": 1},
    "scatter":      {"cards": [13],     "docs": 7,  "method": "AddScatter", "block": 0},
    "waterfall":    {"cards": [24],     "docs": 8,  "method": "AddWaterfall", "block": 0},
    "gauge":        {"cards": [25],     "docs": 9,  "method": "AddGauge", "block": 0},
    "data-ring":    {"cards": [39, 40], "docs": 10, "method": "AddDataRing", "block": 0},
    "bubble":       {"cards": [46],     "docs": 11, "method": "AddBubble", "block": 0},
    "heatmap":      {"cards": [47],     "docs": 12, "method": "AddHeatmap", "block": 0},
    "column-range": {"cards": [48],     "docs": 13, "method": "AddColumnRange", "block": 0},
    "area-range":   {"cards": [49],     "docs": 14, "method": "AddAreaRange", "block": 0},
    "funnel":       {"cards": [50],     "docs": 15, "method": "AddFunnel", "block": 0},
    "treemap":      {"cards": [51],     "docs": 16, "method": "AddTreemap", "block": 0},
    "radar":        {"cards": [63],     "docs": 17, "method": "AddRadar", "block": 0},
    "box-plot":     {"cards": [64],     "docs": 18, "method": "AddBoxPlot", "block": 0},
    "error-bar":    {"cards": [65],     "docs": 19, "method": "AddErrorBar", "block": 0},
    "candlestick":  {"cards": [70],     "docs": 20, "method": "AddCandlestick", "block": 0},
    "ohlc":         {"cards": [71],     "docs": 21, "method": "AddOhlc", "block": 0},
    "dumbbell":     {"cards": [95],     "docs": 22, "method": "AddDumbbell", "block": 0},
    "stream":       {"cards": [96],     "docs": 23, "method": "AddStream", "block": 0},
    "gantt":        {"cards": [97],     "docs": 24, "method": "AddGantt", "block": 0},
    "sankey":       {"cards": [98],     "docs": 25, "method": "AddSankey", "block": 0},
    "parliament":   {"cards": [60],     "docs": 26, "method": "AddParliament", "block": 0},
}

FEATURES: dict[str, dict] = {
    "themes-and-fills": {
        "cards": [15, 16, 73, 75, 32, 33, 34, 66, 67, 68],
        "title": "Chart Themes and Fills in C# — Dark, Pastel, Vivid, Gradient",
        "h1": "Chart Themes and Fills in C#",
        "nav_title": "Themes and Fills",
        "description": "Restyle any TerraFluent chart in C#: 18 built-in themes "
                       "including dark and high-contrast, plus gradient fills, "
                       "pattern fills, borders and marker styling.",
        "lede": "Every chart below is the same builder call with a different theme "
                "or fill applied. Themes are a single `.Theme(...)` call and change "
                "nothing about your data code.",
        "docs": "/docs/chart/themes-and-styling/",
    },
    "axes-and-scales": {
        "cards": [22, 26, 44, 61, 62, 82, 102, 23, 69, 77],
        "title": "Chart Axes and Scales in C# — Log, Date-Time, Secondary Y",
        "h1": "Chart Axes and Scales in C#",
        "nav_title": "Axes and Scales",
        "description": "Configure chart axes in C#: secondary Y-axis, logarithmic "
                       "and date-time scales, inverted axes, tick intervals, plot "
                       "bands, threshold zones and target lines.",
        "lede": "Axis configuration is where most real charts need work — two series "
                "on incompatible scales, a log axis for a wide range, or a reference "
                "band the reader has to see.",
        "docs": "/docs/chart/api-reference/#axes",
    },
    "labels-legends-tooltips": {
        "cards": [17, 27, 29, 30, 31, 35, 36, 72, 74],
        "title": "Chart Labels, Legends and Tooltips in C#",
        "h1": "Chart Labels, Legends and Tooltips in C#",
        "nav_title": "Labels, Legends and Tooltips",
        "description": "Control data labels, legend placement, tooltip styling and "
                       "annotations on C# SVG charts — formatting, positioning and "
                       "collision-aware label layout.",
        "lede": "Labels, legends and tooltips carry the chart's text, which is also "
                "the part search engines and screen readers can read. All of it is "
                "real SVG text, not a bitmap.",
        "docs": "/docs/chart/api-reference/#datalabeloptions",
    },
    "stacking-and-combos": {
        "cards": [5, 19, 20, 21, 79, 2, 8, 80, 81],
        "title": "Stacked and Combination Charts in C#",
        "h1": "Stacked and Combination Charts in C#",
        "nav_title": "Stacking and Combos",
        "description": "Build grouped, stacked and 100% stacked charts in C#, plus "
                       "mixed-type and dual-axis combination charts, all as "
                       "self-contained SVG.",
        "lede": "Stacking and mixing series types are properties of the chart, not "
                "separate chart types — any cartesian series can participate.",
        "docs": "/docs/chart/api-reference/#series",
    },
    "render-modes": {
        "cards": [9, 10, 14, 42, 43, 78],
        "title": "Chart Render Modes in C# — Static, Animated, Interactive",
        "h1": "Chart Render Modes in C#",
        "nav_title": "Render Modes",
        "description": "Choose how a C# chart renders: Static SVG for PDF and email, "
                       "Animated SMIL, or Interactive with embedded JavaScript. Fixed "
                       "or responsive width, and data-URI output.",
        "lede": "The render mode decides what ships in the SVG. Static is pure markup "
                "for PDF and email clients, Animated adds SMIL, and Interactive is the "
                "only mode that emits JavaScript.",
        "docs": "/docs/chart/api-reference/#render-mode",
    },
    "interactivity": {
        "cards": [52, 53, 54, 55, 56, 57, 86, 99, 100],
        "title": "Interactive SVG Charts in C# — Click, Export, Range Selector",
        "h1": "Interactive SVG Charts in C#",
        "nav_title": "Interactivity",
        "description": "Add click handlers, legend toggles, SVG and PNG export, a data "
                       "table toggle, a range selector and synchronized tooltips to C# "
                       "charts — browser-only, opt-in.",
        "lede": "Interactive mode is opt-in. Everything on this page requires "
                "`.AsInteractive()` and a browser; none of it appears in Static output.",
        "docs": "/docs/chart/advanced/",
    },
    "accessibility-and-culture": {
        "cards": [87, 88, 89, 76],
        "title": "Accessible and Localized Charts in C# — ARIA, RTL, Culture",
        "h1": "Accessible and Localized Charts in C#",
        "nav_title": "Accessibility and Culture",
        "description": "Make C# SVG charts accessible and localized: custom ARIA "
                       "labels, right-to-left layout, CultureInfo number and date "
                       "formatting, and explicit null-gap policy.",
        "lede": "Every chart carries a `<title>` and `<desc>` and `aria-label`s by "
                "default. These examples override them, switch direction, and format "
                "for a non-English culture.",
        "docs": "/docs/chart/api-reference/#accessibility--localization",
        "notes": [
            "**The chart is text, not a picture.** Output is inline SVG whose labels, "
            "titles and legends are real `<text>` nodes. A screen reader reads them, "
            "a crawler indexes them, and Ctrl+F finds them — none of which is true of "
            "a chart shipped as a PNG.",
            "**Every chart is labelled by default.** Each SVG gets a `<title>` and a "
            "`<desc>`, wired up with `aria-labelledby` and `aria-describedby`, and the "
            "`<desc>` summarises the series and value range in words. Override either "
            "when you have better context than the generator does.",
            "**Culture affects more than the decimal separator.** Passing a "
            "`CultureInfo` changes number grouping, date formats and currency "
            "placement together, so a de-DE chart reads 1.234,5 and a date axis "
            "follows the same culture rather than drifting to the invariant format.",
            "**Right-to-left is a layout change, not a text change.** RTL mirrors the "
            "axis order and legend placement as well as the label direction, which is "
            "what an Arabic or Hebrew reader expects.",
            "**Gaps must be a decision.** `GapPolicy` decides whether a `null` breaks "
            "the line or is bridged. Leaving it implicit means a missing measurement "
            "and a measured zero can end up drawn the same way.",
            "**Colour is never the only channel.** Marker symbols, fill patterns and "
            "the high-contrast theme keep series distinguishable for readers with "
            "colour-vision deficiency, and in greyscale print.",
        ],
    },
    "analytics-overlays": {
        "cards": [58, 59, 83, 84, 85],
        "title": "Trend Line and Analytics Overlays in C# Charts",
        "h1": "Trend Lines and Analytics Overlays in C#",
        "nav_title": "Analytics Overlays",
        "description": "Add computed series to C# charts: linear regression trend "
                       "lines, moving averages, exponential smoothing, and AutoInsight "
                       "annotations derived from the data.",
        "lede": "Overlay series are derived from data already on the chart — you pass "
                "the source array and the library computes the rest.",
        "docs": "/docs/chart/api-reference/#computed-overlays",
    },
}

RECIPES = {
    "cards": [41, 45, 90, 91, 92, 93, 94, 101],
    "title": "C# Chart Cookbook — Dashboards, Templates, Drill-Down",
    "h1": "C# Chart Cookbook",
    "nav_title": "Cookbook",
    "description": "Complete C# chart recipes: KPI dashboards, prebuilt report "
                   "templates, chart variants with Fork, JSON round-trip "
                   "serialization and drill-down charts.",
    "lede": "Each recipe is a finished result rather than a single feature — the "
            "kind of chart you ship, assembled from several calls.",
    "docs": "/docs/chart/advanced/",
}

SECTION = "Chart Reporting"
SECTION_URL = "/chart/"


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

class Card:
    """One `<div class="card">` sliced out of the upstream showcase."""

    __slots__ = ("number", "heading", "blurb", "body")

    def __init__(self, number: int, heading: str, blurb: str, body: str):
        self.number = number
        self.heading = heading   # the title with the "NN — " prefix stripped
        self.blurb = blurb
        self.body = body         # the inner markup of .card-body, SVG untouched


def parse_cards(source: str) -> list[Card]:
    starts = [m.start() for m in re.finditer(r'<div class="card">', source)]
    if not starts:
        sys.exit("ERROR: no cards found in the showcase source — has the upstream "
                 "markup changed? Expected '<div class=\"card\">'.")
    # The cards are the last thing in <main>; everything after the final card is
    # the closing grid/main wrapper.
    tail = source.rindex("</main>")
    bounds = starts + [source.rindex("</div>", 0, tail)]

    cards = []
    for i, start in enumerate(starts):
        chunk = source[start:bounds[i + 1]]
        heading_m = re.search(r"<h2>(.*?)</h2>", chunk, re.S)
        if not heading_m:
            sys.exit(f"ERROR: card {i + 1} has no <h2>.")
        heading = re.sub(r"\s+", " ", heading_m.group(1)).strip()
        # Upstream numbers every heading "01 &mdash; Line Chart". The number is
        # positional, not meaningful, and it wastes the most valuable text on
        # the page, so it is dropped here and never re-emitted.
        heading = re.sub(r"^\d+\s*(?:&mdash;|&#8212;|—|-)\s*", "", heading)

        blurb_m = re.search(r"<p>(.*?)</p>", chunk, re.S)
        blurb = re.sub(r"\s+", " ", blurb_m.group(1)).strip() if blurb_m else ""

        body_m = re.search(r'<div class="card-body">(.*)</div>\s*</div>\s*$',
                           chunk, re.S)
        if not body_m:
            sys.exit(f"ERROR: card {i + 1} ({heading}) has no .card-body.")
        cards.append(Card(i + 1, heading, blurb, body_m.group(1).strip()))
    return cards


def parse_snippets(markdown: str) -> dict[int, list[str]]:
    """Map the "## N." sections of chart-types.md to their C# fences."""
    out: dict[int, list[str]] = {}
    sections = re.split(r"^## (\d+)\.\s", markdown, flags=re.M)
    for i in range(1, len(sections), 2):
        number = int(sections[i])
        out[number] = re.findall(r"```csharp\n(.*?)\n```", sections[i + 1], re.S)
    return out


# ---------------------------------------------------------------------------
# Emitting
# ---------------------------------------------------------------------------

def specimen(card: Card, heading_level: str = "h2") -> str:
    """Wrap one card's SVG in the site's figure chrome.

    The SVG markup itself is passed through byte for byte — it already carries
    its own scoped <style>, <title>, <desc> and aria-* attributes, and
    re-rendering it here is impossible anyway (the renderer is the C# library).
    """
    parts = [
        '<figure class="spec">',
        f'  <figcaption class="spec-caption">',
        f'    <{heading_level}>{card.heading}</{heading_level}>',
    ]
    if card.blurb:
        parts.append(f"    <p>{card.blurb}</p>")
    parts += [
        "  </figcaption>",
        '  <div class="spec-frame">',
        card.body,
        "  </div>",
        "</figure>",
    ]
    return "\n".join(parts)


def front_matter(fields: dict) -> str:
    """Emit YAML front matter, key order preserved.

    Long descriptions are collapsed to a single line first so PyYAML wraps them
    on word boundaries rather than folding whatever newlines the source had.
    """
    clean = {
        k: re.sub(r"\s+", " ", v).strip() if isinstance(v, str) else v
        for k, v in fields.items()
    }
    dumped = yaml.safe_dump(
        clean,
        allow_unicode=True,
        sort_keys=False,
        default_flow_style=False,
        width=88,
    ).rstrip()
    return f"---\n{dumped}\n---"


def write(path: Path, text: str, written: list[Path], check: bool) -> None:
    if check:
        written.append(path)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    written.append(path)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="parse and validate without writing any file")
    args = ap.parse_args()

    if not SOURCE.exists():
        sys.exit(f"ERROR: {SOURCE.relative_to(ROOT)} not found. Run mirror-docs.sh "
                 "first, or see scripts/README.md for how to download it.")

    source = SOURCE.read_text(encoding="utf-8")
    cards = parse_cards(source)
    by_number = {c.number: c for c in cards}
    snippets = parse_snippets(DOCS_TYPES.read_text(encoding="utf-8"))
    prose = yaml.safe_load(PROSE.read_text(encoding="utf-8"))

    # ---- validate the classification against what upstream actually shipped --
    claimed: dict[int, str] = {}
    def claim(numbers, owner):
        for n in numbers:
            if n not in by_number:
                sys.exit(f"ERROR: {owner} claims card {n}, which does not exist "
                         f"(the source has {len(cards)} cards). Upstream has "
                         "renumbered the showcase — update the map in this file.")
            if n in claimed:
                sys.exit(f"ERROR: card {n} claimed by both {claimed[n]} and {owner}.")
            claimed[n] = owner

    for slug, spec in TYPES.items():
        claim(spec["cards"], f"types/{slug}")
    for slug, spec in FEATURES.items():
        claim(spec["cards"], f"features/{slug}")
    claim(RECIPES["cards"], "cookbook")

    orphans = sorted(set(by_number) - set(claimed))
    if orphans:
        listing = "\n".join(f"    {n:3d}  {by_number[n].heading}" for n in orphans)
        sys.exit(f"ERROR: {len(orphans)} showcase card(s) are not classified, so "
                 f"their specimens would be silently dropped:\n{listing}\n"
                 "  Add each to TYPES, FEATURES or RECIPES in this file.")

    missing_prose = sorted(set(TYPES) - set(prose))
    if missing_prose:
        sys.exit(f"ERROR: _data/chart_types.yml has no entry for: {missing_prose}")

    written: list[Path] = []
    spokes = {"types": [], "features": [], "cookbook": None}

    # ---- type pages --------------------------------------------------------
    for slug, spec in TYPES.items():
        p = prose[slug]
        fences = snippets.get(spec["docs"], [])
        if len(fences) <= spec["block"]:
            sys.exit(f"ERROR: docs/chart/chart-types.md section {spec['docs']} has "
                     f"no C# example at index {spec['block']} (needed by {slug}).")
        snippet = fences[spec["block"]]

        fm = front_matter({
            "layout": "default",
            "type_slug": slug,
            "title": p["title"],
            "nav_title": p["nav_title"],
            "description": p["description"],
            "permalink": f"/chart/types/{slug}/",
            "doc_section": SECTION,
            "doc_section_url": SECTION_URL,
            "generated_by": "scripts/split_showcase.py",
        })
        body = [
            fm,
            "",
            "<!-- Generated by scripts/split_showcase.py — do not edit by hand.",
            f"     Prose lives in _data/chart_types.yml under `{slug}:`.",
            "     The SVG below is moved verbatim from the upstream showcase, and",
            "     the C# is lifted from docs/chart/chart-types.md. -->",
            "",
            "{% capture specimen %}",
            "\n\n".join(specimen(by_number[n]) for n in spec["cards"]),
            "{% endcapture %}",
            # {% raw %} keeps Liquid's hands off the C#: a snippet containing
            # {{ or {% would otherwise be parsed as a tag and vanish.
            "{% capture snippet %}{% highlight csharp %}{% raw %}",
            snippet,
            "{% endraw %}{% endhighlight %}{% endcapture %}",
            "{% include chart-type-page.html"
            " slug=page.type_slug specimen=specimen snippet=snippet %}",
        ]
        write(ROOT / "chart" / "types" / slug / "index.html",
              "\n".join(body) + "\n", written, args.check)
        spokes["types"].append({
            "slug": slug,
            "url": f"/chart/types/{slug}/",
            "title": p["nav_title"],
            "h1": p["h1"],
            "description": re.sub(r"\s+", " ", p["description"]).strip(),
        })

    # ---- feature pages -----------------------------------------------------
    for slug, spec in FEATURES.items():
        fm = front_matter({
            "layout": "default",
            "title": spec["title"],
            "nav_title": spec["nav_title"],
            "description": spec["description"],
            "permalink": f"/chart/features/{slug}/",
            "doc_section": SECTION,
            "doc_section_url": SECTION_URL,
            "lede": spec["lede"],
            "api_docs": spec["docs"],
            "notes": spec.get("notes", []),
            "generated_by": "scripts/split_showcase.py",
        })
        body = [
            fm,
            "",
            "<!-- Generated by scripts/split_showcase.py — do not edit by hand.",
            "     The SVG below is moved verbatim from the upstream showcase. -->",
            "",
            "{% capture specimens %}",
            "\n\n".join(specimen(by_number[n]) for n in spec["cards"]),
            "{% endcapture %}",
            "{% include chart-gallery-page.html "
            f'current="{spec["nav_title"]}" specimens=specimens %}}',
        ]
        write(ROOT / "chart" / "features" / slug / "index.html",
              "\n".join(body) + "\n", written, args.check)
        spokes["features"].append({
            "slug": slug,
            "url": f"/chart/features/{slug}/",
            "title": spec["nav_title"],
            "h1": spec["h1"],
            "count": len(spec["cards"]),
            "description": re.sub(r"\s+", " ", spec["description"]).strip(),
        })

    # ---- cookbook ----------------------------------------------------------
    fm = front_matter({
        "layout": "default",
        "title": RECIPES["title"],
        "nav_title": RECIPES["nav_title"],
        "description": RECIPES["description"],
        "permalink": "/chart/cookbook/",
        "doc_section": SECTION,
        "doc_section_url": SECTION_URL,
        "lede": RECIPES["lede"],
        "api_docs": RECIPES["docs"],
        "generated_by": "scripts/split_showcase.py",
    })
    write(ROOT / "chart" / "cookbook" / "index.html",
          "\n".join([
              fm, "",
              "<!-- Generated by scripts/split_showcase.py — do not edit by hand.",
              "     The SVG below is moved verbatim from the upstream showcase. -->",
              "",
              "{% capture specimens %}",
              "\n\n".join(specimen(by_number[n]) for n in RECIPES["cards"]),
              "{% endcapture %}",
              "{% include chart-gallery-page.html "
              f'current="{RECIPES["nav_title"]}" specimens=specimens %}}',
          ]) + "\n", written, args.check)
    spokes["cookbook"] = {
        "url": "/chart/cookbook/",
        "title": RECIPES["nav_title"],
        "h1": RECIPES["h1"],
        "count": len(RECIPES["cards"]),
        "description": re.sub(r"\s+", " ", RECIPES["description"]).strip(),
    }

    # ---- the hub -----------------------------------------------------------
    generated = re.search(r"<footer>(.*?)</footer>", source, re.S)
    stamp = html.unescape(re.sub(r"\s+", " ", generated.group(1)).strip()) if generated else ""
    fm = front_matter({
        "layout": "default",
        "title": "C# Chart Showcase — 26 Chart Types Rendered as SVG",
        "nav_title": "Chart Showcase",
        "description": "Browse every TerraFluent.Chart.Reporting chart type and "
                       "feature as live, self-contained SVG rendered from C# — "
                       "26 chart types, 18 themes, zero JavaScript.",
        "permalink": "/chart/showcase/",
        "doc_section": SECTION,
        "doc_section_url": SECTION_URL,
        "upstream_stamp": stamp,
        "specimen_count": len(cards),
        "generated_by": "scripts/split_showcase.py",
    })
    write(ROOT / "chart" / "showcase" / "index.html",
          "\n".join([
              fm, "",
              "<!-- Generated by scripts/split_showcase.py — do not edit by hand.",
              "     The index itself is rendered by _includes/chart-hub-page.html",
              "     from _data/chart_spokes.yml. -->",
              "",
              "{% include chart-hub-page.html %}",
          ]) + "\n", written, args.check)

    # ---- llms.txt ----------------------------------------------------------
    # llms.txt is hand-maintained apart from this one block, which is rewritten
    # between the markers so a chart type added upstream is listed for agents
    # without anyone remembering to edit it.
    lines = ["## Chart type pages", "",
             "One page per chart type — specimen, C# source, and when not to use it.", ""]
    for t in spokes["types"]:
        lines.append(f"- [{t['h1']}](https://terrafluent.dev{t['url']}): {t['description']}")
    lines += ["", "## Chart feature pages", ""]
    for f in spokes["features"]:
        lines.append(f"- [{f['h1']}](https://terrafluent.dev{f['url']}): {f['description']}")
    cb = spokes["cookbook"]
    lines.append(f"- [{cb['h1']}](https://terrafluent.dev{cb['url']}): {cb['description']}")
    block = "\n".join(lines)

    llms = ROOT / "llms.txt"
    text = llms.read_text(encoding="utf-8")
    begin = "<!-- BEGIN chart-spokes (generated by scripts/split_showcase.py) -->"
    end = "<!-- END chart-spokes -->"
    if begin not in text or end not in text:
        sys.exit(f"ERROR: llms.txt is missing the {begin!r} / {end!r} markers.")
    if not args.check:
        head, rest = text.split(begin, 1)
        _, tail = rest.split(end, 1)
        llms.write_text(f"{head}{begin}\n\n{block}\n\n{end}{tail}",
                        encoding="utf-8", newline="\n")

    # ---- llms-full.txt -----------------------------------------------------
    # mirror-docs.sh rebuilds llms-full.txt from the library docs alone, so the
    # when-to-use guidance on the type pages — the one part of the site that is
    # written here rather than mirrored — was missing from the corpus an agent
    # reads. Appended under a marker so re-running this alone replaces the block
    # instead of stacking copies of it.
    full_lines = [
        "",
        "",
        "====================================================================",
        "TerraFluent.Chart.Reporting — Choosing a chart type",
        "URL: https://terrafluent.dev/chart/showcase/",
        "====================================================================",
        "",
        "One page per chart type, each with a live SVG specimen and the C# that",
        "renders it. The guidance below is about fit: which type answers which",
        "question, and where each one misleads.",
        "",
    ]
    for t in spokes["types"]:
        pr = prose[t["slug"]]
        full_lines += [
            f"## {pr['h1']}",
            f"URL: https://terrafluent.dev{t['url']}",
            f"Builder: {TYPES[t['slug']]['method']}",
            "",
            t["description"],
            "",
            "Use it when:",
        ]
        full_lines += [f"  - {x}" for x in pr["use"]]
        full_lines += ["", "Use something else when:"]
        full_lines += [f"  - {x}" for x in pr["avoid"]]
        full_lines += ["", f"Related: {', '.join(pr['related'])}", ""]

    llms_full = ROOT / "llms-full.txt"
    if not args.check and llms_full.exists():
        ft = llms_full.read_text(encoding="utf-8")
        fbegin = "<!-- BEGIN chart-type-guidance (generated by scripts/split_showcase.py) -->"
        fend = "<!-- END chart-type-guidance -->"
        body = f"{fbegin}\n" + "\n".join(full_lines) + f"\n{fend}\n"
        if fbegin in ft and fend in ft:
            head, rest = ft.split(fbegin, 1)
            _, tail = rest.split(fend, 1)
            ft = f"{head}{body}{tail.lstrip()}"
        else:
            ft = ft.rstrip("\n") + "\n\n" + body
        llms_full.write_text(ft, encoding="utf-8", newline="\n")

    if not args.check:
        SPOKES_YML.write_text(
            "# Generated by scripts/split_showcase.py — do not edit by hand.\n"
            "# The URL list for the chart hub-and-spoke pages.\n"
            + yaml.safe_dump(spokes, allow_unicode=True, sort_keys=False, width=100),
            encoding="utf-8", newline="\n")

    verb = "would write" if args.check else "wrote"
    print(f"{verb} {len(written)} page(s) from {len(cards)} specimens: "
          f"{len(TYPES)} type, {len(FEATURES)} feature, 1 cookbook, 1 hub")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
